name: null
favicon: null
layout_spectrum: 0.7303566301707178
typography_spectrum: 0.14255828433670104
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9761261169333011
  lightness: 0.9545410322025418
  saturation: 0.48768039606511593
  rhythmicContrast: 0.738577525364235
purpose: []
